# Generated by Django 6.0.2 on 2026-02-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_portuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portuser',
            name='followers',
        ),
    ]
