# Generated by Django 6.0.2 on 2026-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_portuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='portuser',
            name='avatar',
            field=models.CharField(blank=True, choices=[('war', 'War'), ('conquest', 'Conquest'), ('famine', 'Famine'), ('death', 'Death')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
