# Generated by Django 6.0.2 on 2026-06-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_portuser_avatar_portuser_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portuser',
            name='notify_on_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='notify_on_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='notify_on_list_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='notify_on_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='notify_on_watchlist',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
