# Generated by Django 6.0.2 on 2026-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_portuser_notify_on_comment_portuser_notify_on_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
