# Generated by Django 6.0.2 on 2026-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_portuser_bio_portuser_location_portuser_pronouns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='portuser',
            name='avatar',
            field=models.CharField(blank=True, choices=[('war', 'War'), ('conquest', 'Conquest'), ('famine', 'Famine'), ('death', 'Death')], default='death', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portuser',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them')], default='they/them', max_length=20, null=True),
        ),
    ]
