# Generated by Django 6.0.2 on 2026-07-12 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_portuser_phone_alter_portuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
