# Generated by Django 6.0.2 on 2026-07-17 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContentRelations', '0008_alter_contentrelations_favourited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('watched_status', models.CharField(choices=[('watched', 'Watched'), ('rewatched', 'Rewatched')], default='watched', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ContentRelations.contentrelations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
