# Generated by Django 6.0.2 on 2026-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='contains_spoilers',
            field=models.BooleanField(default=False),
        ),
    ]
