export const sampleMovies = [
  {
    adult: false,
    backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
    genre_ids: [16, 35, 10751],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them.",
    popularity: 5741.89,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.7,
    vote_count: 4289,
  },
  {
    adult: false,
    backdrop_path: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for double murder, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
    popularity: 84.87,
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 21000,
  },
  {
    adult: false,
    backdrop_path: "/lh4aGpd3U9rm9B8Oqr6CUgQLtZL.jpg",
    genre_ids: [28, 12, 878],
    id: 603,
    original_language: "en",
    original_title: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the machines.",
    popularity: 111.13,
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: "1999-03-30",
    title: "The Matrix",
    video: false,
    vote_average: 8.1,
    vote_count: 19346,
  },
  {
    adult: false,
    backdrop_path: "/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    genre_ids: [18, 80],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and DA Harvey Dent, Batman sets out to dismantle organized crime in Gotham City.",
    popularity: 87.23,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-18",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 25670,
  },
  {
    adult: false,
    backdrop_path: "/avqzw36ZB5IWRxrU3T5lAZjsqL9.jpg",
    genre_ids: [16, 35, 10751],
    id: 672,
    original_language: "en",
    original_title: "Harry Potter and the Chamber of Secrets",
    overview:
      "Harry Potter's second year at Hogwarts is marked by the mystery of a secret chamber and a monster terrorizing the school.",
    popularity: 70.01,
    poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
    release_date: "2002-11-13",
    title: "Harry Potter and the Chamber of Secrets",
    video: false,
    vote_average: 7.7,
    vote_count: 11920,
  },
  {
    adult: false,
    backdrop_path: "/6cT3Yd3LzZ6uzxhB8MPvD1TxjS6.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and other historic events unfold from the perspective of an Alabama man with a low IQ.",
    popularity: 60.34,
    poster_path: "/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg",
    release_date: "1994-07-06",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.4,
    vote_count: 21960,
  },]