export const sampleMovies = [
  {
    adult: false,
    backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
    genre_ids: [16, 35, 10751],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them.",
    popularity: 5741.89,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.7,
    vote_count: 4289,
    duration: 87,
    release_year: 2022
  },
  {
    adult: false,
    backdrop_path: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for double murder, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
    popularity: 84.87,
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 21000,
    duration: 142,
    release_year: 1994
  },
  {
    adult: false,
    backdrop_path: "/lh4aGpd3U9rm9B8Oqr6CUgQLtZL.jpg",
    genre_ids: [28, 12, 878],
    id: 603,
    original_language: "en",
    original_title: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the machines.",
    popularity: 111.13,
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: "1999-03-30",
    title: "The Matrix",
    video: false,
    vote_average: 8.1,
    vote_count: 19346,
    duration: 136,
    release_year: 1999
  },
  {
    adult: false,
    backdrop_path: "/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    genre_ids: [18, 80],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and DA Harvey Dent, Batman sets out to dismantle organized crime in Gotham City.",
    popularity: 87.23,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-18",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 25670,
    duration: 152,
    release_year: 2008
  },
  {
    adult: false,
    backdrop_path: "/avqzw36ZB5IWRxrU3T5lAZjsqL9.jpg",
    genre_ids: [16, 35, 10751],
    id: 672,
    original_language: "en",
    original_title: "Harry Potter and the Chamber of Secrets",
    overview:
      "Harry Potter's second year at Hogwarts is marked by the mystery of a secret chamber and a monster terrorizing the school.",
    popularity: 70.01,
    poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
    release_date: "2002-11-13",
    title: "Harry Potter and the Chamber of Secrets",
    video: false,
    vote_average: 7.7,
    vote_count: 11920,
    duration: 161,
    release_year: 2002
  },
  {
    adult: false,
    backdrop_path: "/6cT3Yd3LzZ6uzxhB8MPvD1TxjS6.jpg",
    genre_ids: [35, 18, 10749],
    id: 13445,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "The presidencies of Kennedy and Johnson, the Vietnam War, and other historic events unfold from the perspective of an Alabama man with a low IQ.",
    popularity: 60.34,
    poster_path: "/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg",
    release_date: "1994-07-06",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.4,
    vote_count: 21960,
    duration: 142,
    release_year: 1994
  },
  {
    adult: false,
    backdrop_path: "/o1nTo4fo5rV8mIEGoJr0LNmTXbW.jpg",
    genre_ids: [35, 18, 10749],
    id: 13232,
    original_language: "en",
    original_title: "The Pursuit of Happyness",
    overview:
      "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional endeavor.",
    popularity: 80.45,
    poster_path: "/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
    release_date: "2006-12-15",
    title: "The Pursuit of Happyness",
    video: false,
    vote_average: 8.0,
    vote_count: 10000,
    duration: 117,
    release_year: 2006
  },
  {
    adult: false,
    backdrop_path: "/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
    genre_ids: [18],
    id: 550,
    original_language: "en",
    original_title: "Fight Club",
    overview:
      "An insomniac office worker and a soap maker form an underground club that evolves into something much more.",
    popularity: 95.5,
    poster_path: "/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg",
    release_date: "1999-10-15",
    title: "Fight Club",
    video: false,
    vote_average: 8.8,
    vote_count: 24000,
    duration: 139,
    release_year: 1999
  },
  {
    adult: false,
    backdrop_path: "/vL5LR6WdxWPjLPfrJ1mxxOeo26E.jpg",
    genre_ids: [12, 14, 28],
    id: 671,
    original_language: "en",
    original_title: "Harry Potter and the Philosopher's Stone",
    overview:
      "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family, and the dark forces that threaten the magical world.",
    popularity: 900,
    poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    release_date: "2001-11-16",
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    vote_average: 7.9,
    vote_count: 21000,
    duration: 152,
    release_year: 2001
  }
];
