# Generated by Django 6.0.1 on 2026-01-24 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
