# Generated by Django 6.0.1 on 2026-01-26 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0002_contentrelations_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrelations',
            old_name='likes',
            new_name='liked',
        ),
        migrations.AlterField(
            model_name='contentrelations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
