# Generated by Django 6.0.1 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0003_rename_likes_contentrelations_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrelations',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='contentrelations',
            name='poster_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contentrelations',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentrelations',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
