# Generated by Django 6.0.2 on 2026-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0004_contentrelations_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelations',
            name='media_type',
            field=models.CharField(choices=[('film', 'Film'), ('tv', 'TV')], default='movie', max_length=10),
        ),
    ]
