# Generated by Django 6.0.2 on 2026-06-05 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0005_alter_contentrelations_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentrelations',
            name='favourited',
        ),
        migrations.AddField(
            model_name='contentrelations',
            name='favourite_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
