# Generated by Django 6.0.2 on 2026-06-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0006_remove_contentrelations_favourited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentrelations',
            old_name='favourite_rank',
            new_name='favourited',
        ),
    ]
