# Generated by Django 6.0.2 on 2026-06-09 09:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentRelations', '0007_rename_favourite_rank_contentrelations_favourited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrelations',
            name='favourited',
            field=models.IntegerField(blank=True, choices=[(0, '1st'), (1, '2nd'), (2, '3rd'), (3, '4th')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='contentrelations',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='contentrelations',
            constraint=models.UniqueConstraint(fields=('user', 'tmdb_id'), name='unique_user_tmdb_relation'),
        ),
    ]
